export const archiveEnglish = {
  "archive.tab": "Conversation archive",
  "archive.hint": "Archive only communications that pass through this system. Legacy history is not imported automatically. Official WhatsApp call recording is not supported yet.",
  "archive.capture": "Archive new conversations and supported audio",
  "archive.retention": "Enable automatic deletion after conversation closure",
  "archive.hours": "Original retention after closure (hours)",
  "archive.days": "Summary retention after closure (days)",
  "archive.notice": "I have approved the customer notice, lawful basis and retention policy. Copies in backups, Chatwoot and external webhooks require separate deletion policies.",
  "archive.aiEnabled": "Allow explicitly requested OpenAI text summaries",
  "archive.aiModel": "OpenAI model ID",
  "archive.aiNotice": "Generating sends saved text to OpenAI with store:false; this does not guarantee zero provider retention. Audio is not transcribed or sent. AI drafts require human review and are not a substitute for original evidence.",
  "archive.empty": "No archived conversations. Enable archiving and receive a new conversation through this system.",
  "archive.open": "Open conversation",
  "archive.closed": "Closed conversation",
  "archive.expired": "Originals deleted under the retention policy",
  "archive.summary": "Summary / support notes",
  "archive.summarySource": "Summary source",
  "archive.manual": "Reviewed manual summary",
  "archive.metadata": "Metadata only — message/audio counts, not a content summary",
  "archive.draft": "OpenAI draft — not reviewed",
  "archive.close": "Close conversation and start retention period",
  "archive.order": "Linked order number",
  "archive.verify": "I verified the customer and order match / the complaint is resolved before releasing a hold.",
  "archive.link": "Link verified order",
  "archive.hold": "Protect originals for a complaint / legal hold",
  "archive.reason": "Reason / resolution",
  "archive.until": "Hold review deadline",
  "archive.holdHint": "A hold never expires automatically. Review the deadline and explicitly release it only after the matter is resolved.",
  "archive.release": "Release hold after resolution",
  "archive.messages": "Messages (latest 500)",
  "archive.audio": "Voice messages and call recordings",
  "archive.download": "Download protected audio",
  "archive.voice": "Original WhatsApp voice message",
  "archive.call": "Mixed call: original remote voice + audio sent to the caller (may be translated). Not both original voices or a complete translated transcript.",
  "archive.pending": "Audio download pending",
  "archive.unavailable": "Audio unavailable / not retained",
  "archive.generate": "Generate OpenAI draft from saved text",
  "archive.aiConsent": "I approve sending this conversation's saved text to OpenAI now.",
  "archive.audit": "Access and change audit",
  "archive.saved": "Archive settings or conversation updated",
  "archive.action": "Action",
  "archive.actor": "Administrator credential fingerprint",
  "errors.archive_invalid_policy": "Check retention periods and model ID.",
  "errors.archive_notice_required": "Approve the privacy notice and data disclosure first.",
  "errors.archive_model_required": "Configure an OpenAI model ID and server API key.",
  "errors.archive_verification_required": "Verify the customer/order or complaint resolution before continuing.",
  "errors.archive_hold_invalid": "Enter a hold reason and a future review deadline.",
  "errors.archive_originals_expired": "The originals have already expired; they cannot be recovered by adding a hold.",
  "errors.archive_summary_failed": "The summary provider did not return a complete usable result. No summary was replaced.",
  "errors.archive_ai_disabled": "OpenAI summaries are disabled or the server key is missing.",
  "errors.archive_no_text": "No saved text is available to summarize. Audio has not been transcribed.",
  "errors.archive_summary_too_large": "This conversation exceeds the summary size limit. Write a reviewed manual summary.",
} as const;

export const archiveArabic: Record<keyof typeof archiveEnglish, string> = {
  "archive.tab": "أرشيف المحادثات",
  "archive.hint": "تُؤرشف فقط الاتصالات التي تمر عبر نظامنا. لا يُستورد السجل القديم تلقائيًا. تسجيل مكالمات واتساب الرسمي غير مدعوم حاليًا.",
  "archive.capture": "أرشفة المحادثات الجديدة والصوت المدعوم",
  "archive.retention": "تفعيل الحذف التلقائي بعد إغلاق المحادثة",
  "archive.hours": "الاحتفاظ بالأصول بعد الإغلاق (بالساعات)",
  "archive.days": "الاحتفاظ بالملخص بعد الإغلاق (بالأيام)",
  "archive.notice": "اعتمدت إشعار العميل والأساس النظامي وسياسة الاحتفاظ. النسخ الاحتياطية ونسخ Chatwoot والإشعارات الخارجية تحتاج سياسات حذف مستقلة.",
  "archive.aiEnabled": "السماح بملخصات OpenAI النصية عند الطلب الصريح",
  "archive.aiModel": "معرّف نموذج OpenAI",
  "archive.aiNotice": "يُرسل النص المحفوظ إلى OpenAI مع store:false؛ وهذا لا يضمن انعدام الاحتفاظ لدى المزود. لا يُرسل الصوت ولا يُفرّغ. مسودة الذكاء الاصطناعي تحتاج مراجعة بشرية وليست بديلًا عن الأدلة الأصلية.",
  "archive.empty": "لا توجد محادثات مؤرشفة. فعّل الأرشفة ثم استقبل محادثة جديدة عبر النظام.",
  "archive.open": "محادثة مفتوحة",
  "archive.closed": "محادثة مغلقة",
  "archive.expired": "حُذفت الأصول وفق سياسة الاحتفاظ",
  "archive.summary": "الملخص وملاحظات الدعم",
  "archive.summarySource": "مصدر الملخص",
  "archive.manual": "ملخص يدوي مراجع",
  "archive.metadata": "بيانات وصفية فقط: أعداد الرسائل والصوت، وليس ملخص محتوى",
  "archive.draft": "مسودة OpenAI لم تُراجع",
  "archive.close": "إغلاق المحادثة وبدء مدة الاحتفاظ",
  "archive.order": "رقم الطلب المرتبط",
  "archive.verify": "تحققت من تطابق العميل والطلب، أو من إغلاق الشكوى قبل رفع تعليق الحذف.",
  "archive.link": "ربط الطلب بعد التحقق",
  "archive.hold": "حماية الأصول لشكوى أو تعليق حذف نظامي",
  "archive.reason": "سبب التعليق أو نتيجة المعالجة",
  "archive.until": "موعد مراجعة تعليق الحذف",
  "archive.holdHint": "لا ينتهي تعليق الحذف تلقائيًا. راجع الموعد وارفع التعليق صراحةً بعد حل الموضوع فقط.",
  "archive.release": "رفع تعليق الحذف بعد الحل",
  "archive.messages": "الرسائل (آخر 500)",
  "archive.audio": "الرسائل الصوتية وتسجيلات المكالمات",
  "archive.download": "تنزيل الصوت المحمي",
  "archive.voice": "رسالة واتساب الصوتية الأصلية",
  "archive.call": "مكالمة ممزوجة: صوت الطرف الآخر الأصلي والصوت المرسل إليه (قد يكون مترجمًا). ليست تسجيلاً لكل الأصوات الأصلية ولا تفريغًا مترجمًا كاملاً.",
  "archive.pending": "تنزيل الصوت قيد الانتظار",
  "archive.unavailable": "الصوت غير متاح أو لم يُحتفظ به",
  "archive.generate": "إنشاء مسودة OpenAI من النص المحفوظ",
  "archive.aiConsent": "أوافق على إرسال نص هذه المحادثة المحفوظ إلى OpenAI الآن.",
  "archive.audit": "سجل الوصول والتغييرات",
  "archive.saved": "حُفظت إعدادات الأرشيف أو المحادثة",
  "archive.action": "الإجراء",
  "archive.actor": "بصمة مفتاح المسؤول",
  "errors.archive_invalid_policy": "راجع مدد الاحتفاظ ومعرّف النموذج.",
  "errors.archive_notice_required": "اعتمد إشعار الخصوصية ومشاركة البيانات أولاً.",
  "errors.archive_model_required": "حدد معرّف نموذج OpenAI ومفتاح الخدمة على الخادم.",
  "errors.archive_verification_required": "تحقق من تطابق العميل والطلب أو حل الشكوى قبل المتابعة.",
  "errors.archive_hold_invalid": "أدخل سبب تعليق الحذف وموعد مراجعة مستقبليًا.",
  "errors.archive_originals_expired": "انتهت مدة الأصول وحُذفت؛ تعليق الحذف الآن لا يستعيدها.",
  "errors.archive_summary_failed": "لم يُرجع مزود الملخص نتيجة مكتملة صالحة. لم يُستبدل الملخص السابق.",
  "errors.archive_ai_disabled": "ملخصات OpenAI معطلة أو مفتاح الخادم غير موجود.",
  "errors.archive_no_text": "لا يوجد نص محفوظ للتلخيص. لم يُفرّغ الصوت إلى نص.",
  "errors.archive_summary_too_large": "المحادثة تتجاوز حد حجم التلخيص. اكتب ملخصًا يدويًا مراجعًا.",
};
