export const adminCompletionEnglish = {
  "adminStock.tab": "Stock",
  "adminStock.hint": "Stock is saved separately from the menu. Available units are sellable now; held units are already reserved for orders.",
  "adminStock.tracked": "Track this item's stock",
  "adminStock.untracked": "Stock not tracked",
  "adminStock.available": "Available units",
  "adminStock.held": "Reserved units",
  "adminStock.edit": "Adjust stock",
  "adminStock.saved": "Stock updated.",
  "adminStock.conflict": "Stock changed while you were editing. Refresh and review the latest quantities before saving again.",
  "adminStock.menuHint": "Use Stock to manage sellable quantities. Menu availability remains a separate on/off setting.",
  "adminStock.select": "Select an item to adjust its stock.",
  "adminSupport.title": "Customer requests",
  "adminSupport.cancellation": "Cancellation request",
  "adminSupport.reason": "Reason",
  "adminSupport.decisionReason": "Decision reason",
  "adminSupport.approve": "Approve cancellation",
  "adminSupport.reject": "Reject cancellation",
  "adminSupport.approveConfirm": "Approve cancellation of order #{number}? Any payment refund must be handled separately.",
  "adminSupport.rejectConfirm": "Reject the cancellation request for order #{number} with this reason?",
  "adminSupport.cancellationSaved": "Cancellation decision recorded.",
  "adminSupport.requested": "Awaiting restaurant decision",
  "adminSupport.approved": "Cancellation approved",
  "adminSupport.rejected": "Cancellation rejected",
  "adminSupport.preparationStarted": "Preparation started",
  "adminSupport.stockExpires": "Stock reservation expires",
  "adminSupport.beforePreparation": "Requested before preparation started",
  "adminSupport.complaints": "Complaints",
  "adminSupport.open": "Open complaint",
  "adminSupport.resolved": "Resolved complaint",
  "adminSupport.resolution": "Resolution details",
  "adminSupport.resolve": "Record resolution",
  "adminSupport.resolveConfirm": "Mark this complaint as resolved with the entered explanation?",
  "adminSupport.resolvedNotice": "Complaint resolution recorded.",
  "adminRefund.title": "Refunds",
  "adminRefund.hint": "A cancellation does not automatically refund a payment. Pending requests reserve the refund amount; only a verified provider result confirms an electronic refund.",
  "adminRefund.captured": "Captured payment",
  "adminRefund.reserved": "Pending or manually reported refunds",
  "adminRefund.confirmed": "Provider-confirmed refunds",
  "adminRefund.available": "Remaining refundable amount",
  "adminRefund.amount": "Refund amount",
  "adminRefund.fullRemaining": "Use full remaining amount",
  "adminRefund.create": "Request refund",
  "adminRefund.execute": "Authorize provider refund",
  "adminRefund.latePayment": "Payment was verified after the order was cancelled.",
  "adminRefund.verifyReference": "Verify original provider refund",
  "adminRefund.verifyReferenceHint": "Find the original refund in your merchant dashboard and enter its reference. This only verifies that existing refund; do not send another refund while its outcome is unknown.",
  "adminRefund.confirm": "Request a refund of {amount} for order #{number}? This may send a real financial request to the payment provider.",
  "adminRefund.saved": "Refund request recorded. Review its confirmation status below.",
  "adminRefund.empty": "No refund requests have been recorded.",
  "adminRefund.unavailable": "No refundable balance is currently available.",
  "adminRefund.manualOnly": "Automatic refunds are unavailable for this payment. Refund it outside this system, then record the outcome with a reference.",
  "adminRefund.fullOnly": "This payment supports full remaining refunds only.",
  "adminRefund.status.requested": "Refund requested",
  "adminRefund.status.processing": "Provider processing — not confirmed",
  "adminRefund.status.succeeded": "Provider-confirmed refund",
  "adminRefund.status.failed": "Refund failed",
  "adminRefund.status.review": "Refund needs review",
  "adminRefund.status.manual_reported": "Manually reported — not provider-confirmed",
  "adminRefund.confirmation.none": "No refund confirmation",
  "adminRefund.confirmation.provider": "Confirmed by payment provider",
  "adminRefund.confirmation.manual": "Reported manually by restaurant",
  "adminRefund.manual": "Record an external refund",
  "adminRefund.reference": "External refund reference",
  "adminRefund.manualWarning": "Only record a refund you have already completed outside this system. This does not verify that money reached the customer's bank.",
  "adminRefund.manualConfirm": "Record an external refund of {amount} with this reference? This is a manual report, not provider confirmation.",
  "adminRefund.manualSaved": "External refund reported. It is not provider-confirmed.",
  "adminRefund.refreshHint": "Check the provider for the latest refund result",
  "adminRefund.unknown": "The result is not yet known. Retry the same request to avoid creating a duplicate refund.",
} as const;

export const adminCompletionArabic: Record<keyof typeof adminCompletionEnglish, string> = {
  "adminStock.tab": "المخزون",
  "adminStock.hint": "يُحفظ المخزون بشكل مستقل عن المنيو. الكمية المتاحة قابلة للبيع الآن، والكمية المحجوزة مخصصة لطلبات قائمة.",
  "adminStock.tracked": "تتبّع مخزون هذا الصنف",
  "adminStock.untracked": "المخزون غير متتبّع",
  "adminStock.available": "الكمية المتاحة",
  "adminStock.held": "الكمية المحجوزة",
  "adminStock.edit": "تعديل المخزون",
  "adminStock.saved": "حُدّث المخزون.",
  "adminStock.conflict": "تغيّر المخزون أثناء التعديل. حدّث البيانات وراجع الكميات الحالية قبل الحفظ مجددًا.",
  "adminStock.menuHint": "استخدم المخزون لإدارة الكميات القابلة للبيع. يظل تفعيل إتاحة الصنف في المنيو إعدادًا مستقلاً.",
  "adminStock.select": "اختر صنفًا لتعديل مخزونه.",
  "adminSupport.title": "طلبات العملاء",
  "adminSupport.cancellation": "طلب إلغاء",
  "adminSupport.reason": "السبب",
  "adminSupport.decisionReason": "سبب القرار",
  "adminSupport.approve": "الموافقة على الإلغاء",
  "adminSupport.reject": "رفض الإلغاء",
  "adminSupport.approveConfirm": "هل توافق على إلغاء الطلب #{number}؟ يجب معالجة استرداد أي دفعة بشكل منفصل.",
  "adminSupport.rejectConfirm": "هل ترفض طلب إلغاء الطلب #{number} مع تسجيل هذا السبب؟",
  "adminSupport.cancellationSaved": "سُجّل قرار الإلغاء.",
  "adminSupport.requested": "بانتظار قرار المطعم",
  "adminSupport.approved": "تمت الموافقة على الإلغاء",
  "adminSupport.rejected": "رُفض الإلغاء",
  "adminSupport.preparationStarted": "بدأ التجهيز",
  "adminSupport.stockExpires": "ينتهي حجز المخزون",
  "adminSupport.beforePreparation": "طُلب الإلغاء قبل بدء التجهيز",
  "adminSupport.complaints": "الشكاوى",
  "adminSupport.open": "شكوى مفتوحة",
  "adminSupport.resolved": "شكوى محلولة",
  "adminSupport.resolution": "تفاصيل الحل",
  "adminSupport.resolve": "تسجيل الحل",
  "adminSupport.resolveConfirm": "هل تسجّل حل هذه الشكوى مع التوضيح المُدخل؟",
  "adminSupport.resolvedNotice": "سُجّل حل الشكوى.",
  "adminRefund.title": "الاستردادات",
  "adminRefund.hint": "إلغاء الطلب لا يعيد المدفوعات تلقائيًا. تحجز الطلبات المعلقة مبلغ الاسترداد، ولا يتأكد الاسترداد الإلكتروني إلا بنتيجة موثّقة من مزوّد الدفع.",
  "adminRefund.captured": "الدفعة المحصّلة",
  "adminRefund.reserved": "استردادات معلقة أو مبلّغ عنها يدويًا",
  "adminRefund.confirmed": "استردادات أكدها المزوّد",
  "adminRefund.available": "المبلغ المتبقي القابل للاسترداد",
  "adminRefund.amount": "مبلغ الاسترداد",
  "adminRefund.fullRemaining": "استخدام المبلغ المتبقي بالكامل",
  "adminRefund.create": "طلب استرداد",
  "adminRefund.execute": "تفويض الاسترداد عبر المزوّد",
  "adminRefund.latePayment": "تأكد الدفع بعد إلغاء الطلب.",
  "adminRefund.verifyReference": "التحقق من استرداد المزوّد الأصلي",
  "adminRefund.verifyReferenceHint": "ابحث عن الاسترداد الأصلي في لوحة التاجر وأدخل مرجعه. هذا الإجراء يتحقق من الاسترداد الموجود فقط؛ لا ترسل استردادًا آخر ما دامت نتيجته غير معروفة.",
  "adminRefund.confirm": "هل تطلب استرداد {amount} للطلب #{number}؟ قد يُرسل طلب مالي فعلي إلى مزوّد الدفع.",
  "adminRefund.saved": "سُجّل طلب الاسترداد. راجع حالة تأكيده أدناه.",
  "adminRefund.empty": "لم تُسجّل طلبات استرداد بعد.",
  "adminRefund.unavailable": "لا يوجد حاليًا رصيد متاح للاسترداد.",
  "adminRefund.manualOnly": "الاسترداد التلقائي غير متاح لهذه الدفعة. أعد المبلغ خارج النظام ثم سجّل النتيجة مع مرجع العملية.",
  "adminRefund.fullOnly": "تدعم هذه الدفعة استرداد المبلغ المتبقي بالكامل فقط.",
  "adminRefund.status.requested": "طُلب الاسترداد",
  "adminRefund.status.processing": "قيد معالجة المزوّد — غير مؤكد",
  "adminRefund.status.succeeded": "استرداد أكده المزوّد",
  "adminRefund.status.failed": "فشل الاسترداد",
  "adminRefund.status.review": "الاسترداد يحتاج إلى مراجعة",
  "adminRefund.status.manual_reported": "مبلّغ عنه يدويًا — لم يؤكده المزوّد",
  "adminRefund.confirmation.none": "لا يوجد تأكيد للاسترداد",
  "adminRefund.confirmation.provider": "أكده مزوّد الدفع",
  "adminRefund.confirmation.manual": "أبلغ عنه المطعم يدويًا",
  "adminRefund.manual": "تسجيل استرداد خارجي",
  "adminRefund.reference": "مرجع الاسترداد الخارجي",
  "adminRefund.manualWarning": "سجّل فقط استردادًا أنجزته بالفعل خارج النظام. هذا التسجيل لا يثبت وصول المبلغ إلى بنك العميل.",
  "adminRefund.manualConfirm": "هل تسجّل استردادًا خارجيًا بقيمة {amount} بهذا المرجع؟ هذا بلاغ يدوي وليس تأكيدًا من المزوّد.",
  "adminRefund.manualSaved": "سُجّل بلاغ الاسترداد الخارجي. لم يؤكده المزوّد.",
  "adminRefund.refreshHint": "التحقق من أحدث نتيجة للاسترداد لدى المزوّد",
  "adminRefund.unknown": "لم تُعرف النتيجة بعد. أعد محاولة الطلب نفسه لتجنب إنشاء استرداد مكرر.",
};
