export const adminEnglish = {
  "admin.title": "Restaurant dashboard", "admin.orders": "Orders", "admin.menu": "Menu",
  "admin.tables": "Tables & QR codes", "admin.settings": "Restaurant settings", "admin.calls": "Calls dashboard",
  "admin.storefront": "Open restaurant", "admin.subtitle": "Your menu, tables and orders in one place.",
  "admin.allStatuses": "All statuses", "admin.searchOrders": "Search order number, name or phone",
  "admin.noOrders": "No orders match your filters.", "admin.selectOrder": "Select an order to see its details.",
  "admin.live": "Orders refresh every 5 seconds", "admin.customer": "Customer", "admin.openMap": "Open location on map",
  "admin.updateStatus": "Update order status", "admin.nextStatus": "Next status", "admin.items": "Dishes",
  "admin.catalogHint": "Save your changes to publish the menu, tables and restaurant settings.",
  "admin.unsaved": "You have unpublished changes.", "admin.publish": "Save and publish", "admin.discard": "Discard changes",
  "admin.discardConfirm": "Discard all unpublished changes?", "admin.conflict": "Someone updated this restaurant. Reload the latest version before saving your changes.",
  "admin.reload": "Reload latest version", "admin.categories": "Categories", "admin.addCategory": "Add category",
  "admin.category": "Category", "admin.name": "Name", "admin.sort": "Display order", "admin.addItem": "Add dish",
  "admin.noItems": "Add your first dish to start building the menu.", "admin.description": "Description",
  "admin.price": "Price", "admin.priceHint": "Enter an amount in {currency}.", "admin.available": "Available",
  "admin.options": "Extras and options", "admin.addOption": "Add option", "admin.optionPriceHint": "Set the price to zero for a free option.",
  "admin.imageUrl": "Image URL", "admin.uploadImage": "Upload image", "admin.imageHint": "JPG or PNG, up to 5 MB. Remote image links must use HTTPS.",
  "admin.removeConfirm": "Remove this item?", "admin.categoryInUse": "Move or remove the dishes in this category first.",
  "admin.addTable": "Add table", "admin.active": "Active", "admin.noTables": "Add tables to create individual ordering QR codes.",
  "admin.tableHint": "Each QR opens the menu for that table. Existing orders stay separate.",
  "admin.saveTableFirst": "Save and publish to create this table's QR code.", "admin.copyLink": "Copy table link",
  "admin.printQR": "Print QR code", "admin.scanOrder": "Scan to order", "admin.tableDisabled": "This table is disabled for new orders.",
  "admin.restaurantName": "Restaurant name", "admin.restaurantAddress": "Restaurant address", "admin.restaurantPhone": "Restaurant phone",
  "admin.logoUrl": "Logo URL", "admin.currency": "Currency", "admin.defaultLanguage": "Default interface language",
  "admin.menuLanguage": "Menu content language", "admin.keepMenuLanguage": "Keep the existing menu language", "admin.openingHours": "Opening hours", "admin.pickupInstructions": "Pickup instructions",
  "admin.paymentInstructions": "Payment instructions", "admin.demo": "Label this restaurant and its orders as demo",
  "admin.acceptingOrders": "Accept new orders", "admin.orderModes": "Order methods", "admin.deliverySettings": "Delivery settings",
  "admin.deliveryAreas": "Delivery areas (one per line)", "admin.deliveryFee": "Delivery fee", "admin.deliveryMinimum": "Minimum delivery subtotal",
  "admin.deliveryRadius": "Delivery radius in kilometres (0 for no radius limit)", "admin.latitude": "Latitude", "admin.longitude": "Longitude",
  "admin.requireLocation": "Require the customer's location for delivery", "admin.radiusHint": "A delivery radius requires a valid restaurant latitude and longitude.",
  "admin.validation": "Check the required fields, amounts and image URLs before saving.", "admin.saveSuccess": "Restaurant changes published.",
  "admin.statusSuccess": "Order status updated.", "admin.copyError": "The link could not be copied. Select and copy it from the field.",
  "admin.cancelOrderConfirm": "Cancel this order?", "admin.orderMode": "Order method", "admin.enabled": "Enabled",
} as const;
