// Locale-extension source for the Arabic and English restaurant interface.
export const adminNextEnglish = {
  "payments.field.apiId": "API ID",
  "payments.field.secretKey": "Secret key", "payments.field.entityId": "Entity ID", "payments.field.accessToken": "Access token",
  "payments.field.profileId": "Profile ID", "payments.field.serverKey": "Server key", "payments.field.merchantPublicKey": "Merchant public key",
  "payments.field.apiPassword": "API password", "payments.field.apiToken": "API token", "payments.field.paymentMethodId": "Payment method ID",
  "adminNext.brand": "Restaurant appearance", "adminNext.brandHint": "Preview your changes here, then save and publish to update the customer menu.",
  "adminNext.primaryColor": "Primary color", "adminNext.accentColor": "Accent color", "adminNext.backgroundColor": "Background color",
  "adminNext.cover": "Cover image", "adminNext.logo": "Restaurant logo", "adminNext.preview": "Preview", "adminNext.resetBrand": "Restore default appearance",
  "adminNext.resetBrandConfirm": "Restore the default colors and clear the logo and cover in this draft? Publish to apply the change.",
  "adminNext.previewHint": "Preview only — your customer menu changes after publishing.", "adminNext.colorError": "Use a color in #RRGGBB format.",
  "adminNext.country": "Restaurant country", "adminNext.tax": "Tax settings", "adminNext.taxEnabled": "Show tax included in prices",
  "adminNext.taxRate": "Tax rate (%)", "adminNext.taxNumber": "Tax registration number", "adminNext.taxHint": "Menu prices, extras and delivery fees already include tax. Enabling tax extracts it from the total and never adds it again.",
  "adminNext.taxCompliance": "Enable this only for your restaurant's applicable tax registration. These receipts are not certified ZATCA electronic invoices.",
  "adminNext.paymentPolicy": "Payment methods by order type", "adminNext.pickupCardOnly": "Pickup orders require card payment.",
  "adminNext.paymentPolicyHint": "Card checkout becomes available only when a payment provider is configured and enabled. Orders with advance cash or card payment cannot enter preparation until payment is confirmed.",
  "adminNext.payments": "Payment gateways", "adminNext.paymentGatewayHint": "Configure your own merchant account. Credentials are write-only and stored on the server.",
  "adminNext.provider": "Provider", "adminNext.mode": "Environment", "adminNext.testMode": "Test mode", "adminNext.liveMode": "Live mode",
  "adminNext.gatewayEnabled": "Enable this payment gateway", "adminNext.configured": "Configured", "adminNext.notConfigured": "Setup required",
  "adminNext.secretSaved": "Saved — leave blank to keep", "adminNext.clearSecret": "Clear saved credential", "adminNext.secretHint": "Blank secret fields keep existing values. Clearing a saved credential can make this gateway unavailable.",
  "adminNext.gatewaySaved": "Payment gateway configuration saved.", "adminNext.liveConfirm": "Enable live payments with this merchant account? Customer checkout can create real payment requests.",
  "adminNext.stripeSaudi": "Stripe availability for a Saudi merchant depends on Stripe's supported business countries and your account eligibility. A Saudi restaurant must not assume it can activate a local Stripe account.",
  "adminNext.providerNotTested": "Configuration does not confirm that the merchant account is activated or that a real payment has succeeded.",
  "adminNext.sarOnly": "These payment integrations currently support SAR transactions only.",
  "adminNext.demoModeRule": "Demo restaurants use test payment gateways only. Restaurants with demo mode turned off use live gateways only.",
  "adminNext.providerLimit.merchant_sar_currency": "MyFatoorah requires a merchant account whose base currency is SAR. Demo accounts with KWD as their base currency cannot be used.",
  "adminNext.providerLimit.paylink_sandbox_only": "Experimental Paylink sandbox only, minimum SAR 5. Live payments, account webhooks and automatic refunds are unavailable. Sandbox account acceptance and external-key security checks are still required.",
  "adminNext.providerLimit.hyperpay_test_only": "HyperPay currently supports test mode only. Live checkout is unavailable.",
  "adminNext.providerLimit.merchant_mode_credentials": "Test mode requires your provider's test merchant credentials. Selecting test mode cannot turn live merchant credentials into a sandbox account.",
  "adminNext.metaWebhook": "Meta webhook URL", "adminNext.metaSecretHint": "Credentials are kept on the server. Leave saved secret fields blank to keep their existing values.",
  "adminNext.webhook": "Payment webhook URL", "adminNext.payment": "Payment", "adminNext.cashConfirm": "Confirm cash collected",
  "adminNext.cashConfirmPrompt": "Confirm that {amount} has actually been collected in cash for this order?", "adminNext.cashSuccess": "Cash collection recorded.",
  "adminNext.paymentBlocked": "Payment must be collected before this status change.", "adminNext.taxNet": "Amount before tax", "adminNext.taxIncluded": "Included tax",
  "adminNext.couriers": "Couriers", "adminNext.courierHint": "Create separate courier logins. Each courier sees only their active assigned delivery orders.",
  "adminNext.addCourier": "Add courier", "adminNext.noCouriers": "No couriers yet. Add a courier to assign deliveries.",
  "adminNext.courierLogin": "Courier sign-in page", "adminNext.courierActive": "Courier account enabled", "adminNext.availability": "Availability",
  "adminNext.resetPassword": "Set a new password", "adminNext.passwordHint": "Use at least 10 characters. Leave blank to keep the current password.",
  "adminNext.courierSaved": "Courier account saved.", "adminNext.courier": "Assigned courier", "adminNext.unassigned": "Unassigned",
  "adminNext.assignCourier": "Save assignment", "adminNext.assignmentSuccess": "Courier assignment updated.", "adminNext.assignmentHint": "Reassigning immediately removes the previous courier's access to this order.",
  "adminNext.deliveryStatus": "Delivery progress", "adminNext.deliveryHistory": "Delivery history"
} as const;

export const adminNextArabic: Record<keyof typeof adminNextEnglish, string> = {
  "payments.field.apiId": "معرّف الواجهة",
  "payments.field.secretKey": "المفتاح السري", "payments.field.entityId": "معرّف الكيان", "payments.field.accessToken": "رمز الوصول",
  "payments.field.profileId": "معرّف الملف", "payments.field.serverKey": "مفتاح الخادم", "payments.field.merchantPublicKey": "المفتاح العام للتاجر",
  "payments.field.apiPassword": "كلمة مرور الواجهة", "payments.field.apiToken": "رمز الواجهة", "payments.field.paymentMethodId": "معرّف طريقة الدفع",
  "adminNext.brand": "مظهر المطعم", "adminNext.brandHint": "عاين التغييرات هنا، ثم احفظ وانشر لتحديث المنيو الذي يراه العميل.",
  "adminNext.primaryColor": "اللون الأساسي", "adminNext.accentColor": "اللون المميز", "adminNext.backgroundColor": "لون الخلفية",
  "adminNext.cover": "صورة الغلاف", "adminNext.logo": "شعار المطعم", "adminNext.preview": "معاينة", "adminNext.resetBrand": "استعادة المظهر الافتراضي",
  "adminNext.resetBrandConfirm": "هل تستعيد الألوان الافتراضية وتمسح الشعار والغلاف من هذه المسودة؟ انشر لتطبيق التغيير.",
  "adminNext.previewHint": "هذه معاينة فقط؛ يتغير منيو العميل بعد النشر.", "adminNext.colorError": "استخدم لونًا بصيغة #RRGGBB.",
  "adminNext.country": "بلد المطعم", "adminNext.tax": "إعدادات الضريبة", "adminNext.taxEnabled": "إظهار الضريبة المشمولة في الأسعار",
  "adminNext.taxRate": "نسبة الضريبة (%)", "adminNext.taxNumber": "رقم التسجيل الضريبي", "adminNext.taxHint": "أسعار المنيو والإضافات ورسوم التوصيل شاملة للضريبة. تفعيل الضريبة يستخرجها من الإجمالي ولا يضيفها مرة أخرى.",
  "adminNext.taxCompliance": "فعّل هذا الخيار وفق التسجيل الضريبي المنطبق على مطعمك. هذه الإيصالات ليست فواتير إلكترونية معتمدة من هيئة الزكاة والضريبة والجمارك.",
  "adminNext.paymentPolicy": "طرق الدفع حسب نوع الطلب", "adminNext.pickupCardOnly": "طلبات الاستلام تتطلب الدفع بالبطاقة.",
  "adminNext.paymentPolicyHint": "يتاح الدفع بالبطاقة بعد إعداد بوابة دفع وتفعيلها. الطلبات المدفوعة نقدًا مقدمًا أو بالبطاقة لا تدخل التجهيز قبل تأكيد الدفع.",
  "adminNext.payments": "بوابات الدفع", "adminNext.paymentGatewayHint": "أعدّ حساب التاجر الخاص بك. بيانات الاعتماد تُرسل للحفظ فقط وتُخزن على الخادم.",
  "adminNext.provider": "المزوّد", "adminNext.mode": "بيئة التشغيل", "adminNext.testMode": "وضع الاختبار", "adminNext.liveMode": "الوضع الفعلي",
  "adminNext.gatewayEnabled": "تفعيل بوابة الدفع هذه", "adminNext.configured": "مُعدّة", "adminNext.notConfigured": "تحتاج إلى إعداد",
  "adminNext.secretSaved": "محفوظ — اتركه فارغًا للاحتفاظ به", "adminNext.clearSecret": "مسح بيانات الاعتماد المحفوظة", "adminNext.secretHint": "ترك الحقول السرية فارغة يحتفظ بالقيم الحالية. مسح بيانات اعتماد محفوظة قد يوقف إتاحة البوابة.",
  "adminNext.gatewaySaved": "حُفظ إعداد بوابة الدفع.", "adminNext.liveConfirm": "هل تفعّل المدفوعات الفعلية بحساب التاجر هذا؟ قد ينشئ تأكيد العميل طلبات دفع حقيقية.",
  "adminNext.stripeSaudi": "إتاحة Stripe للتاجر السعودي تعتمد على بلدان الأعمال التي تدعمها Stripe وأهلية حسابك. لا ينبغي افتراض إمكانية تفعيل حساب Stripe محلي لمطعم سعودي.",
  "adminNext.providerNotTested": "حفظ الإعداد لا يؤكد تفعيل حساب التاجر أو نجاح عملية دفع حقيقية.",
  "adminNext.sarOnly": "تكاملات الدفع الحالية تدعم عمليات الريال السعودي فقط.",
  "adminNext.demoModeRule": "المطاعم التجريبية تستخدم بوابات الاختبار فقط. عند إيقاف وضع المطعم التجريبي، تُستخدم البوابات الفعلية فقط.",
  "adminNext.providerLimit.merchant_sar_currency": "يتطلب MyFatoorah حساب تاجر عملته الأساسية الريال السعودي. لا يمكن استخدام الحسابات التجريبية التي عملتها الأساسية الدينار الكويتي.",
  "adminNext.providerLimit.paylink_sandbox_only": "Paylink تجريبي فقط، والحد الأدنى 5 ريالات. الدفع الفعلي وإشعارات الحساب والاسترداد الآلي غير متاحة. ما زال اختبار الحساب التجريبي والتحقق من حماية المفاتيح الخارجية مطلوبين.",
  "adminNext.providerLimit.hyperpay_test_only": "يدعم HyperPay وضع الاختبار فقط حاليًا. تأكيد الدفع الفعلي غير متاح.",
  "adminNext.providerLimit.merchant_mode_credentials": "وضع الاختبار يتطلب بيانات اعتماد حساب تجريبي من المزوّد. اختيار وضع الاختبار لا يحوّل بيانات اعتماد التاجر الفعلية إلى حساب تجريبي.",
  "adminNext.metaWebhook": "رابط Webhook لـMeta", "adminNext.metaSecretHint": "تُحفظ بيانات الاعتماد على الخادم. اترك الحقول السرية المحفوظة فارغة للاحتفاظ بقيمها الحالية.",
  "adminNext.webhook": "رابط استقبال إشعارات الدفع", "adminNext.payment": "الدفع", "adminNext.cashConfirm": "تأكيد تحصيل النقد",
  "adminNext.cashConfirmPrompt": "هل تؤكد تحصيل {amount} نقدًا بالفعل لهذا الطلب؟", "adminNext.cashSuccess": "سُجل تحصيل النقد.",
  "adminNext.paymentBlocked": "يجب تحصيل الدفع قبل تغيير الحالة إلى هذه المرحلة.", "adminNext.taxNet": "المبلغ قبل الضريبة", "adminNext.taxIncluded": "الضريبة المشمولة",
  "adminNext.couriers": "المندوبون", "adminNext.courierHint": "أنشئ حسابات مستقلة للمندوبين. يرى كل مندوب طلبات التوصيل النشطة المسندة إليه فقط.",
  "adminNext.addCourier": "إضافة مندوب", "adminNext.noCouriers": "لا يوجد مندوبون بعد. أضف مندوبًا لإسناد طلبات التوصيل.",
  "adminNext.courierLogin": "صفحة دخول المندوب", "adminNext.courierActive": "حساب المندوب مفعّل", "adminNext.availability": "التوفر",
  "adminNext.resetPassword": "تعيين كلمة مرور جديدة", "adminNext.passwordHint": "استخدم 10 أحرف على الأقل. اتركه فارغًا للاحتفاظ بكلمة المرور الحالية.",
  "adminNext.courierSaved": "حُفظ حساب المندوب.", "adminNext.courier": "المندوب المسند إليه", "adminNext.unassigned": "غير مسند",
  "adminNext.assignCourier": "حفظ الإسناد", "adminNext.assignmentSuccess": "حُدّث إسناد المندوب.", "adminNext.assignmentHint": "إعادة الإسناد تمنع المندوب السابق فورًا من الوصول إلى هذا الطلب.",
  "adminNext.deliveryStatus": "تقدم التوصيل", "adminNext.deliveryHistory": "سجل التوصيل"
};
