export const customerCompletionEnglish = {
  "location.title": "Courier location", "location.start": "Share my location for this delivery", "location.stop": "Stop sharing location",
  "location.consent": "Share your current location only for this assigned delivery. The customer and restaurant can see it while the job is active. You can stop at any time.",
  "location.limit": "Keep this page open. Browsers may pause updates when the phone is locked or the app is in the background. Location is not proof of delivery or payment.",
  "location.sharing": "Location sharing is on", "location.stopped": "Location sharing is off", "location.unavailable": "No recent location is being shared.",
  "location.stale": "This location is out of date; the courier may be offline.", "location.updated": "Last location update", "location.accuracy": "Approximate accuracy: {meters} m",
  "location.denied": "Location permission was not granted. You can continue the delivery without sharing your location.",
  "location.failed": "Location could not be updated. Check your connection and try again.",
  "location.showMap": "Load map", "location.hideMap": "Hide map", "location.mapPrivacy": "Loading the map sends your IP address and the approximate map area to OpenStreetMap. Your private order number, access code and exact marker coordinates are not sent.",
  "location.mapUnavailable": "Map tiles are unavailable. You can still use the navigation link.", "location.mapLabel": "Map of courier and delivery destination", "location.zoomIn": "Zoom in", "location.zoomOut": "Zoom out",
  "location.destination": "Delivery destination", "location.courierMarker": "Courier", "location.attribution": "© OpenStreetMap contributors", "location.navigate": "Navigate to destination",
  "support.title": "Order help", "support.cancel": "Request cancellation", "support.problem": "Report a problem", "support.reason": "Tell the restaurant what happened", "support.send": "Send request",
  "support.policy": "Before preparation starts, cancellation may be approved automatically. After preparation starts, the restaurant reviews the request. Cancellation does not confirm that money has been refunded.",
  "support.pending": "Your request is awaiting the restaurant's decision.", "support.cancel.approved": "Cancellation approved", "support.cancel.requested": "Cancellation requested", "support.cancel.rejected": "Cancellation declined",
  "support.complaint.open": "Problem reported", "support.complaint.resolved": "Problem resolved", "support.decision": "Restaurant response", "support.requestSent": "Your request was received.",
  "support.retry": "The result is not confirmed. Retry this same request before starting another one.", "support.stockHint": "Availability is checked again when you confirm the order.",
  "support.stockHold": "Unpaid, unaccepted orders may have a temporary stock reservation. Check the latest order status before paying.",
  "refund.title": "Refund progress", "refund.requested": "Refund requested", "refund.processing": "Refund processing", "refund.review": "Refund under review", "refund.failed": "Refund not completed",
  "refund.succeeded": "Refund confirmed by payment provider", "refund.manual_reported": "Refund reported manually by restaurant", "refund.bankDelay": "A provider-confirmed refund can take additional time to appear at your bank.",
  "refund.manualWarning": "This is a restaurant-reported refund, not confirmation from the payment provider.", "refund.none": "No refund is recorded for this order yet.",
} as const;
export const customerCompletionArabic: Record<keyof typeof customerCompletionEnglish,string> = {
  "location.title":"موقع المندوب", "location.start":"مشاركة موقعي لهذا التوصيل", "location.stop":"إيقاف مشاركة الموقع",
  "location.consent":"شارك موقعك الحالي لهذا الطلب المسند إليك فقط. يستطيع العميل والمطعم رؤيته أثناء نشاط التوصيل، ويمكنك إيقاف المشاركة في أي وقت.",
  "location.limit":"أبقِ الصفحة مفتوحة؛ قد يوقف المتصفح التحديثات عند قفل الهاتف أو الانتقال إلى الخلفية. الموقع ليس إثباتًا للتسليم أو الدفع.",
  "location.sharing":"مشاركة الموقع مفعلة", "location.stopped":"مشاركة الموقع متوقفة", "location.unavailable":"لا يوجد موقع حديث قيد المشاركة.",
  "location.stale":"هذا الموقع قديم؛ ربما يكون المندوب غير متصل.", "location.updated":"آخر تحديث للموقع", "location.accuracy":"الدقة التقريبية: {meters} م",
  "location.denied":"لم تُمنح صلاحية الموقع. يمكنك متابعة التوصيل دون مشاركة موقعك.", "location.failed":"تعذر تحديث الموقع. تحقق من الاتصال ثم حاول مجددًا.",
  "location.showMap":"تحميل الخريطة", "location.hideMap":"إخفاء الخريطة", "location.mapPrivacy":"تحميل الخريطة يرسل عنوان اتصالك والمنطقة التقريبية للخريطة إلى OpenStreetMap. لا يُرسل رقم طلبك الخاص أو رمز الوصول أو الإحداثيات الدقيقة للعلامات.",
  "location.mapUnavailable":"تعذر تحميل مربعات الخريطة. يمكنك استخدام رابط الملاحة.", "location.mapLabel":"خريطة المندوب ووجهة التوصيل", "location.zoomIn":"تكبير", "location.zoomOut":"تصغير",
  "location.destination":"وجهة التوصيل", "location.courierMarker":"المندوب", "location.attribution":"© مساهمو OpenStreetMap", "location.navigate":"الملاحة إلى الوجهة",
  "support.title":"المساعدة في الطلب", "support.cancel":"طلب إلغاء", "support.problem":"الإبلاغ عن مشكلة", "support.reason":"وضح للمطعم ما حدث", "support.send":"إرسال الطلب",
  "support.policy":"قبل بدء التحضير قد يُعتمد الإلغاء تلقائيًا، وبعد بدء التحضير يراجع المطعم الطلب. إلغاء الطلب لا يؤكد إعادة المبلغ.",
  "support.pending":"طلبك بانتظار قرار المطعم.", "support.cancel.approved":"تمت الموافقة على الإلغاء", "support.cancel.requested":"تم طلب الإلغاء", "support.cancel.rejected":"رُفض طلب الإلغاء",
  "support.complaint.open":"تم الإبلاغ عن المشكلة", "support.complaint.resolved":"تم حل المشكلة", "support.decision":"رد المطعم", "support.requestSent":"تم استلام طلبك.",
  "support.retry":"لم تتأكد النتيجة بعد. أعد إرسال الطلب نفسه قبل بدء طلب آخر.", "support.stockHint":"يُتحقق من التوفر مجددًا عند تأكيد الطلب.",
  "support.stockHold":"قد يكون للطلبات غير المدفوعة وغير المقبولة حجز مؤقت للمخزون. تحقق من أحدث حالة للطلب قبل الدفع.",
  "refund.title":"متابعة الاسترداد", "refund.requested":"طُلب استرداد المبلغ", "refund.processing":"الاسترداد قيد المعالجة", "refund.review":"الاسترداد قيد المراجعة", "refund.failed":"لم يكتمل الاسترداد",
  "refund.succeeded":"أكد مزود الدفع الاسترداد", "refund.manual_reported":"أبلغ المطعم عن استرداد يدوي", "refund.bankDelay":"قد يحتاج الاسترداد المؤكد من مزود الدفع وقتًا إضافيًا ليظهر لدى البنك.",
  "refund.manualWarning":"هذا استرداد أبلغ عنه المطعم، وليس تأكيدًا صادرًا عن مزود الدفع.", "refund.none":"لا يوجد استرداد مسجل لهذا الطلب بعد.",
};
