// Semantic source for the customer UI. Locale dictionaries supply every translation.
export const storefrontEnglish = {
  "common.loading": "Loading…",
  "common.retry": "Try again",
  "common.close": "Close",
  "common.save": "Save",
  "common.saved": "Saved",
  "common.cancel": "Cancel",
  "common.back": "Back",
  "common.optional": "Optional",
  "common.remove": "Remove",
  "common.add": "Add",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.refresh": "Refresh",
  "common.error": "Something went wrong. Please try again.",
  "store.menu": "Menu",
  "store.track": "Track an order",
  "store.account": "My account",
  "store.cart": "Your order",
  "store.demo": "Demo restaurant — sample menu and test orders only.",
  "store.heroTag": "Your table. Your time.",
  "store.heroTitle": "Good food, a few taps away.",
  "store.heroText":
    "Browse the menu, choose how to receive your order, and follow it here. No account required.",
  "store.browse": "Explore the menu",
  "store.guest": "Order without signing up",
  "store.all": "All dishes",
  "store.search": "Search the menu",
  "store.noItems": "No dishes found",
  "store.noItemsHint": "Try another search or category.",
  "store.closed": "The restaurant is not accepting new orders right now.",
  "store.emptyCart": "Something delicious belongs here",
  "store.emptyCartHint": "Add your favourite dishes to get started.",
  "store.checkout": "Continue to checkout",
  "store.subtotal": "Subtotal",
  "store.deliveryFee": "Delivery fee",
  "store.total": "Total",
  "store.extras": "Extras",
  "store.quantity": "Quantity",
  "store.addToCart": "Add to order",
  "store.added": "Added to your order",
  "store.unavailable": "Unavailable",
  "store.decrease": "Decrease quantity",
  "store.increase": "Increase quantity",
  "store.menuLanguage":
    "Menu descriptions are provided by the restaurant; changing the interface language does not translate them.",
  "store.tableWelcome": "Ordering for {table}",
  "store.tableHint":
    "Each new order is independent. Keep your order number to follow it.",
  "store.moveExisting": "Move an existing order to this table",
  "store.cartUpdated":
    "Your basket was updated because some dishes or options are no longer available.",
  "order.checkout": "Complete your order",
  "order.noAccount":
    "No registration needed. We only ask for the details needed for your order.",
  "order.how": "How would you like your order?",
  "order.delivery": "Delivery",
  "order.pickup": "Pickup at the restaurant door",
  "order.table": "At a table",
  "order.contact": "Contact details",
  "order.name": "Your name",
  "order.phone": "Phone number",
  "order.notes": "Order notes",
  "order.notesHint": "Anything the restaurant should know?",
  "order.tableCode": "Table QR link or code",
  "order.tableHelp":
    "Scan your table QR with your phone camera or paste its link here.",
  "order.review": "Review order",
  "order.confirm": "Confirm order",
  "order.reviewHint":
    "Check your order and total. No online payment is collected here.",
  "order.edit": "Edit order",
  "order.submitting": "Sending your order…",
  "order.deliveryMinimum": "Minimum delivery order: {amount}",
  "order.deliveryAreas": "Delivery areas: {areas}",
  "order.location": "Use my location",
  "order.locationSet": "Location attached",
  "order.locationError":
    "Location could not be obtained. Check your browser permission and try again.",
  "order.locationRequired":
    "The restaurant requires a location pin for delivery.",
  "order.success": "Your order is received",
  "order.successText":
    "Keep your order number and private tracking link. The restaurant will update the status here.",
  "order.number": "Order number",
  "order.accessCode": "Access code",
  "order.privateLink": "Copy private tracking link",
  "order.privateWarning":
    "Keep this link and access code private. They allow access to your order and table changes.",
  "order.tracking": "Follow your order",
  "order.trackHint":
    "Enter the order number and access code from your receipt.",
  "order.find": "Find my order",
  "order.updated": "Last updated",
  "order.created": "Placed",
  "order.details": "Order details",
  "order.status.new": "Awaiting confirmation",
  "order.status.accepted": "Confirmed",
  "order.status.preparing": "Being prepared",
  "order.status.ready": "Ready",
  "order.status.out_for_delivery": "Out for delivery",
  "order.status.completed": "Completed",
  "order.status.cancelled": "Cancelled",
  "order.changeTable": "Change table",
  "order.newTable": "New table QR link or code",
  "order.changeTableHint":
    "Only this order moves. Its number stays the same and other orders remain unchanged.",
  "order.tableChanged": "Table updated",
  "order.moveToTable": "Move to {table}",
  "order.newOrder": "Start a new order",
  "order.networkRetry":
    "The result of sending your order is not yet confirmed. Retry this same submission to avoid duplicates.",
  "order.unavailableMode": "No order method is currently available.",
  "order.tableHistory": "Table changes",
  "address.title": "Delivery address",
  "address.saved": "Saved addresses",
  "address.manual": "Enter a new address",
  "address.label": "Address label",
  "address.city": "City",
  "address.district": "District",
  "address.street": "Street",
  "address.building": "Building number",
  "address.postalCode": "Postal code",
  "address.additionalNumber": "Additional number",
  "address.nationalAddress": "Saudi national address / short address",
  "address.nationalHint":
    "Use your national address or short address, not your national ID number.",
  "address.addressLine": "Apartment, floor and directions",
  "address.area": "Delivery area",
  "account.title": "Your restaurant account",
  "account.optional":
    "An account is optional. Save addresses and see orders placed while signed in.",
  "account.login": "Sign in",
  "account.register": "Create an account",
  "account.username": "Username",
  "account.password": "Password",
  "account.passwordHint":
    "Use at least 10 characters. Do not reuse an important password.",
  "account.usernameHint":
    "3–40 letters, numbers, dots, hyphens or underscores.",
  "account.displayName": "Display name",
  "account.logout": "Sign out",
  "account.profile": "Your details",
  "account.addresses": "Saved addresses",
  "account.addAddress": "Add an address",
  "account.orders": "Your orders",
  "account.noOrders": "Orders placed while signed in will appear here.",
  "account.noRecovery":
    "This simple account does not verify a phone or email. Keep your username and password safe; there is no automatic password recovery.",
  "account.orderHistoryNote":
    "Guest orders are accessible using their receipt; they are not added to your account automatically.",
  "account.sessionExpired": "Please sign in again to continue.",
  "account.addressLimit": "You can save up to five addresses.",
} as const;
