export const customerNextEnglish = {
  "address.country": "Country",
  "payment.title": "Payment",
  "payment.chooseMethod": "Choose how to pay",
  "payment.chooseProvider": "Card payment provider",
  "payment.reviewHint":
    "Check the order and total. For card payments, confirm your order first, then continue to the secure payment page.",
  "payment.method.cash_before": "Cash before preparation",
  "payment.method.cash_after": "Cash after the meal",
  "payment.method.cash_on_delivery": "Cash on delivery",
  "payment.method.card": "Pay by card online",
  "payment.status.unpaid": "Unpaid",
  "payment.status.pending": "Awaiting payment confirmation",
  "payment.status.paid": "Paid",
  "payment.status.failed": "Payment unsuccessful",
  "payment.status.refunded": "Refunded",
  "payment.status.review": "Payment under review",
  "payment.status.legacy": "Payment not recorded",
  "payment.noProviders":
    "Online payment is not available yet. Contact the restaurant or choose an available cash method.",
  "payment.pickupCardOnly": "Pickup orders require online card payment.",
  "payment.testMode": "Test mode — do not use real card details.",
  "payment.payNow": "Continue to secure payment",
  "payment.refresh": "Check payment status",
  "payment.noRedirectTrust":
    "Returning from a payment page does not confirm payment. We check the payment provider securely.",
  "payment.returnTitle": "Checking your payment",
  "payment.returnHint":
    "Use your private receipt to open the order and check its payment status.",
  "payment.returnMissing":
    "This browser does not have your receipt. Enter your order number and access code to continue.",
  "payment.preparationHold":
    "Preparation begins after the restaurant confirms payment.",
  "payment.legacy": "This older order has no payment record in this system.",
  "payment.cashAwaiting": "Cash has not been marked as collected yet.",
  "payment.checkoutUnavailable":
    "The payment page is not ready. Check the status before trying again.",
  "payment.widgetVerification":
    "Isolated test payment form. This integration requires merchant verification before live payments can be enabled.",
  "tax.inclusive": "Prices include applicable tax.",
  "tax.net": "Amount before tax",
  "tax.amount": "Tax included ({rate}%)",
  "tax.number": "Tax registration number",
  "receipt.print": "Print order receipt",
  "receipt.notFiscal":
    "Order receipt only — this is not a certified ZATCA electronic tax invoice.",
  "courier.title": "Delivery dashboard",
  "courier.loginHint":
    "Sign in with the courier account provided by your restaurant.",
  "courier.availability": "Your availability",
  "courier.availability.available": "Available",
  "courier.availability.busy": "Busy",
  "courier.availability.offline": "Offline",
  "courier.orders": "Your assigned deliveries",
  "courier.empty": "No active deliveries are assigned to you.",
  "courier.callCustomer": "Call customer",
  "courier.openMap": "Open location in maps",
  "courier.collectCash": "I have collected the full cash amount: {amount}",
  "courier.collectRequired":
    "Confirm cash collection before completing this delivery.",
  "courier.readyRequired":
    "Wait until the restaurant marks the order ready for pickup.",
  "courier.cardAwaiting":
    "The card payment must be confirmed before delivery can be completed.",
  "courier.update": "Update delivery status",
  "delivery.title": "Delivery progress",
  "delivery.courier": "Courier",
  "delivery.status.assigned": "Courier assigned",
  "delivery.status.picked_up": "Collected from restaurant",
  "delivery.status.on_the_way": "On the way",
  "delivery.status.nearby": "Nearby",
  "delivery.status.at_door": "At your door",
  "delivery.status.delivered": "Delivered",
  "delivery.noAssignment": "The restaurant has not assigned a courier yet.",
} as const;

export const customerNextArabic: Record<
  keyof typeof customerNextEnglish,
  string
> = {
  "address.country": "الدولة",
  "payment.title": "الدفع",
  "payment.chooseMethod": "اختر طريقة الدفع",
  "payment.chooseProvider": "مزود الدفع بالبطاقة",
  "payment.reviewHint":
    "راجع الطلب والإجمالي. عند الدفع بالبطاقة، أكد طلبك أولًا ثم تابع إلى صفحة الدفع الآمنة.",
  "payment.method.cash_before": "نقدًا قبل التحضير",
  "payment.method.cash_after": "نقدًا بعد الوجبة",
  "payment.method.cash_on_delivery": "نقدًا عند التوصيل",
  "payment.method.card": "الدفع بالبطاقة عبر الإنترنت",
  "payment.status.unpaid": "غير مدفوع",
  "payment.status.pending": "بانتظار تأكيد الدفع",
  "payment.status.paid": "مدفوع",
  "payment.status.failed": "لم تنجح عملية الدفع",
  "payment.status.refunded": "تم رد المبلغ",
  "payment.status.review": "الدفع قيد المراجعة",
  "payment.status.legacy": "الدفع غير مسجل",
  "payment.noProviders":
    "الدفع الإلكتروني غير متاح حاليًا. تواصل مع المطعم أو اختر طريقة نقدية متاحة.",
  "payment.pickupCardOnly": "طلبات الاستلام تتطلب الدفع بالبطاقة عبر الإنترنت.",
  "payment.testMode": "وضع الاختبار — لا تستخدم بيانات بطاقة حقيقية.",
  "payment.payNow": "المتابعة إلى الدفع الآمن",
  "payment.refresh": "التحقق من حالة الدفع",
  "payment.noRedirectTrust":
    "العودة من صفحة الدفع لا تؤكد نجاحه. نتحقق من مزود الدفع بطريقة آمنة.",
  "payment.returnTitle": "جارٍ التحقق من الدفع",
  "payment.returnHint": "استخدم إيصالك الخاص لفتح الطلب والتحقق من حالة دفعه.",
  "payment.returnMissing":
    "لا يوجد إيصالك في هذا المتصفح. أدخل رقم الطلب ورمز الوصول للمتابعة.",
  "payment.preparationHold": "يبدأ التحضير بعد تأكيد المطعم للدفع.",
  "payment.legacy": "هذا الطلب السابق لا يحتوي على سجل دفع في النظام.",
  "payment.cashAwaiting": "لم يتم تسجيل استلام المبلغ النقدي بعد.",
  "payment.checkoutUnavailable":
    "صفحة الدفع غير جاهزة. تحقق من الحالة قبل المحاولة مرة أخرى.",
  "payment.widgetVerification":
    "نموذج دفع اختباري معزول. يتطلب هذا الربط التحقق مع حساب التاجر قبل تفعيل المدفوعات الحقيقية.",
  "tax.inclusive": "الأسعار تشمل الضريبة المطبقة.",
  "tax.net": "المبلغ قبل الضريبة",
  "tax.amount": "الضريبة المشمولة ({rate}٪)",
  "tax.number": "رقم التسجيل الضريبي",
  "receipt.print": "طباعة إيصال الطلب",
  "receipt.notFiscal":
    "إيصال طلب فقط — ليس فاتورة ضريبية إلكترونية معتمدة من هيئة الزكاة والضريبة والجمارك.",
  "courier.title": "لوحة التوصيل",
  "courier.loginHint": "سجّل الدخول بحساب المندوب الذي زودك به المطعم.",
  "courier.availability": "حالة توفرك",
  "courier.availability.available": "متاح",
  "courier.availability.busy": "مشغول",
  "courier.availability.offline": "غير متصل",
  "courier.orders": "طلبات التوصيل المسندة إليك",
  "courier.empty": "لا توجد طلبات توصيل نشطة مسندة إليك.",
  "courier.callCustomer": "الاتصال بالعميل",
  "courier.openMap": "فتح الموقع في الخرائط",
  "courier.collectCash": "استلمت كامل المبلغ النقدي: {amount}",
  "courier.collectRequired": "أكد استلام المبلغ النقدي قبل إكمال التوصيل.",
  "courier.readyRequired": "انتظر حتى يحدد المطعم أن الطلب جاهز للاستلام.",
  "courier.cardAwaiting": "يجب تأكيد الدفع بالبطاقة قبل إكمال التوصيل.",
  "courier.update": "تحديث حالة التوصيل",
  "delivery.title": "متابعة التوصيل",
  "delivery.courier": "المندوب",
  "delivery.status.assigned": "تم تعيين المندوب",
  "delivery.status.picked_up": "تم الاستلام من المطعم",
  "delivery.status.on_the_way": "في الطريق",
  "delivery.status.nearby": "بالقرب منك",
  "delivery.status.at_door": "عند بابك",
  "delivery.status.delivered": "تم التوصيل",
  "delivery.noAssignment": "لم يعيّن المطعم مندوبًا بعد.",
};
