import {openingDayNames,openingWindowsText} from './opening-schedule.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function staffOpeningPage({tenantId,data,csrf,canUpdate,review=null,outcome}){
 const shown=review??data,path='/manage/'+encodeURIComponent(tenantId)+'/opening-schedule';
 const fields={expectedVersion:review?.expectedVersion??data.version,enabled:String(shown.enabled),...Object.fromEntries(shown.weekly.map((windows,i)=>['day'+i,openingWindowsText(windows)])),exceptions:shown.exceptions.map(row=>row.date+' = '+openingWindowsText(row.windows)).join('\n')};
 const hidden=(key,value)=>`<input type="hidden" name="${key}" value="${escape(value)}">`;
 const values=openingDayNames.map((name,i)=>`<p><label>${name}<input dir="ltr" aria-label="${name}" name="day${i}" maxlength="160" value="${escape(fields['day'+i])}" ${canUpdate?'':'readonly'}></label></p>`).join('');
 const form=review?`<h2>مراجعة قبل التطبيق</h2><p>${shown.enabled?'سيُمنع الطلب خارج هذه المواعيد.':'ستُعطل المواعيد الآلية وتبقى سياسة الاستقبال اليدوية.'}</p><ul>${openingDayNames.map((name,i)=>`<li>${name}: <bdi>${escape(fields['day'+i]||'مغلق')}</bdi></li>`).join('')}</ul><pre dir="ltr">${escape(fields.exceptions||'لا توجد استثناءات')}</pre><form method="post" action="${path}/execute">${hidden('csrf',csrf)}${Object.entries(fields).map(([key,value])=>hidden(key,value)).join('')}<label><input type="checkbox" name="reviewed" value="yes" required>راجعت الأيام والاستثناءات وأثر التغيير</label><button>تطبيق المواعيد</button></form><a href="${path}">إلغاء والعودة لأحدث نسخة</a>`:
 `<form method="post" action="${path}/review">${hidden('csrf',csrf)}${hidden('expectedVersion',fields.expectedVersion)}<label>المواعيد الآلية<select name="enabled" ${canUpdate?'':'disabled'}><option value="false" ${shown.enabled?'':'selected'}>معطلة</option><option value="true" ${shown.enabled?'selected':''}>مفعلة</option></select></label>${values}<p><label>استثناءات التواريخ<textarea name="exceptions" rows="5" cols="50" dir="ltr" maxlength="12000" ${canUpdate?'':'readonly'}>${escape(fields.exceptions)}</textarea></label></p>${canUpdate?'<button>مراجعة المواعيد</button>':''}</form>`;
 return `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>مواعيد عمل المطعم</title><h1>مواعيد عمل المطعم</h1><p>${escape(tenantId)} — توقيت السعودية Asia/Riyadh</p><p>اكتب فترات اليوم مثل 09:00-14:00, 17:00-24:00. اليوم الفارغ مغلق. قسّم الدوام الذي يعبر منتصف الليل على يومين. الاستثناء يحل محل اليوم كاملًا، مثل 2026-12-01 = 10:00-16:00؛ اترك ما بعد = فارغًا لإغلاق التاريخ.</p><p>المواعيد لا تفتح مطعمًا أُغلق يدويًا ولا تلغي الطلبات المقبولة.</p>${outcome==='unknown'?'<p role="alert">نتيجة الحفظ السابق غير مؤكدة. هذه أحدث نسخة؛ قارنها قبل أي محاولة جديدة.</p>':''}${form}<p><a href="/manage">رجوع للإدارة</a></p></html>`;
}
