import {RESTAURANT_PERMISSIONS} from './identity-directory.mjs';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const labels={new:'جديد',accepted:'مقبول',preparing:'قيد التحضير',ready:'جاهز',out_for_delivery:'خرج للتوصيل',completed:'مكتمل',cancelled:'ملغي',
  unpaid:'غير مدفوع',pending:'بانتظار التحقق',paid:'مدفوع',failed:'فشل الدفع',refunded:'مسترد',review:'يحتاج مراجعة'};
const label=value=>escape(labels[value]??value);
const page=(title,body)=>`<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><h1>${escape(title)}</h1>${body}</html>`;

export function staffHome(principal,{coreEnabled=true,nativeEnabled=false}={}){
  const sections=[['orders:read','orders',''],['menu:read','menu','منيو '],['stock:read','stock','مخزون '],['channels:manage','channels','قنوات '],['members:manage','members','فريق '],['settings:read','profile','بيانات '],['settings:read','delivery','توصيل '],['settings:read','service','استقبال ']].filter(([,path])=>coreEnabled||path==='members');
  const memberships=principal.memberships.filter(member=>sections.some(([permission])=>member.permissions.includes(permission)));
  const rows=memberships.map(member=>{
    const links=sections.filter(([permission])=>member.permissions.includes(permission)).map(([,path,prefix])=>`<a href="/manage/${escape(member.tenantId)}/${path}">${escape(prefix+member.tenantId)}</a>`).join(' · ');
    return `<li>${links} (${escape(member.role)})</li>`;
  }).join('');
  return page('إدارة المطاعم',`${nativeEnabled?'<a href="/native/sessions">جلسات تطبيق الإدارة</a>':''}<p>معرّف حسابك الداخلي: <span dir="ltr">${escape(principal.id??'')}</span>. شاركه مع مالك المطعم لإضافة عضويتك؛ هذا ليس كلمة مرور.</p><p>اختر المطعم. لا يظهر هنا إلا ما تسمح به عضويتك الحالية.</p><ul>${rows}</ul>${memberships.length?'':'<p>لا توجد عضوية تسمح بالإدارة.</p>'}<a href="/">الصفحة الرئيسية</a>`);
}

export function menuPriceMinor(value){
  if(typeof value!=='string')return null;
  const normalized=value.trim().replace(/[٠-٩]/g,char=>String(char.charCodeAt(0)-0x660)).replace(/[۰-۹]/g,char=>String(char.charCodeAt(0)-0x6f0)).replace(/٫/g,'.');
  if(!/^\d{1,7}(?:\.\d{1,2})?$/.test(normalized))return null;
  const [whole,fraction='']=normalized.split('.');
  const minor=Number(whole)*100+Number(fraction.padEnd(2,'0'));
  return minor<=100_000_000?minor:null;
}

export function staffMenuPage({tenantId,menu,membership,csrf,newItemId,newCategoryId}){
  const categories=new Map(menu.categories.map(category=>[category.id,category.name]));
  const items=menu.items.map(item=>`<li><a href="/manage/${escape(tenantId)}/menu/items/${escape(item.id)}">${escape(item.name)}</a> — ${escape(categories.get(item.categoryId)??item.categoryId)} — ${escape((item.priceMinor/100).toFixed(2))} SAR — ${item.available?'مفعّل في المنيو':'غير مفعّل'}</li>`).join('');
  const hidden=(id)=>`<input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${escape(menu.version)}"><input type="hidden" name="id" value="${escape(id)}">`;
  const create=membership?.permissions.includes('menu:update')?`<section><h2>إضافة قسم</h2><form method="post" action="/manage/${escape(tenantId)}/menu/new-category">${hidden(newCategoryId)}<label>اسم القسم الجديد <input name="name" required maxlength="120"></label><input type="hidden" name="sort" value="0"><button>إضافة القسم</button></form></section>${menu.categories.length?`<section><h2>إضافة صنف</h2><form method="post" action="/manage/${escape(tenantId)}/menu/new-item">${hidden(newItemId)}<label>اسم الصنف الجديد <input name="name" required maxlength="160"></label><label>القسم للصنف الجديد <select name="categoryId">${menu.categories.map(category=>`<option value="${escape(category.id)}">${escape(category.name)}</option>`).join('')}</select></label><label>سعر الصنف الجديد <input name="price" inputmode="decimal" required maxlength="16"></label><button>إضافة الصنف للمراجعة</button></form><p>يُضاف الصنف غير مفعّل حتى تراجع تفاصيله وتفعّله.</p></section>`:'<p>أضف قسمًا أولًا لإضافة الأصناف.</p>'}`:'';
  const categoryEditor=membership?.permissions.includes('menu:update')?`<h2>تعديل الأقسام</h2>${menu.categories.map(category=>`<form method="post" action="/manage/${escape(tenantId)}/menu/categories/${escape(category.id)}"><fieldset><legend>${escape(category.name)}</legend><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${escape(menu.version)}"><label>اسم القسم <input name="name" required maxlength="120" value="${escape(category.name)}"></label><label>ترتيب القسم <input name="sort" type="number" min="0" max="10000" step="1" required value="${escape(category.sort)}"></label><button>حفظ القسم</button></fieldset></form>`).join('')}`:'';
  return page('منيو '+menu.name,`<a href="/manage">مطاعمي</a><p>الإصدار: ${escape(menu.version)}. التغييرات الجديدة لا تعيد تسعير الطلبات السابقة.</p><ul>${items}</ul>${create}${categoryEditor}`);
}

export function staffMenuItemPage({tenantId,membership,menu,csrf,newOptionId}){
  const item=menu.item;
  const options=(item.options??[]).map(option=>`<li>${escape(option.name)}: ${escape((option.priceMinor/100).toFixed(2))} SAR (${option.available?'مفعّل':'غير مفعّل'})</li>`).join('');
  const form=membership.permissions.includes('menu:update')?`<form method="post" action="/manage/${escape(tenantId)}/menu/items/${escape(item.id)}"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${escape(menu.version)}"><label>اسم الصنف <input name="name" required maxlength="320" value="${escape(item.name)}"></label><label>الوصف <textarea name="description" maxlength="4000">${escape(item.description)}</textarea></label><label>السعر بالريال السعودي <input name="price" inputmode="decimal" required maxlength="16" value="${escape((item.priceMinor/100).toFixed(2))}"></label><label>القسم <select name="categoryId">${menu.categories.map(category=>`<option value="${escape(category.id)}" ${item.categoryId===category.id?'selected':''}>${escape(category.name)}</option>`).join('')}</select></label><label>التوفر اليدوي <select name="available"><option value="true" ${item.available?'selected':''}>مفعّل</option><option value="false" ${!item.available?'selected':''}>غير مفعّل</option></select></label><label>الترتيب <input type="number" name="sort" min="0" max="10000" step="1" required value="${escape(item.sort)}"></label><button>حفظ الصنف</button></form>`:'';
  const imageName=/^\/restaurant-media\/([a-f0-9]{64}\.(?:png|jpg))$/.exec(item.imageUrl??'')?.[1];
  const preview=imageName?`<img src="/restaurant-media/${escape(tenantId)}/${imageName}" alt="صورة ${escape(item.name)}" width="320">`:item.imageUrl?'<p>توجد صورة خارجية محفوظة للصنف؛ لا تُحمّل تلقائيًا هنا.</p>':'';
  const imageForm=membership.permissions.includes('menu:update')?`<h2>صورة الصنف</h2>${preview}<form method="post" enctype="multipart/form-data" action="/manage/${escape(tenantId)}/menu/items/${escape(item.id)}/image"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${escape(menu.version)}"><label>صورة PNG أو JPEG <input type="file" name="image" accept="image/png,image/jpeg" required></label><button>رفع وحفظ الصورة</button></form><p>حتى 5 ميغابايت و4096 بكسل لكل بُعد. تُزال بيانات الصورة الوصفية؛ تظهر الصورة للزبائن بعد الحفظ. الصورة السابقة لا تُحذف.</p>`:preview;
  const optionForm=(option,isNew=false)=>`<form method="post" action="/manage/${escape(tenantId)}/menu/items/${escape(item.id)}/options${isNew?'':'/'+escape(option.id)}"><fieldset><legend>${isNew?'إضافة خيار جديد':escape(option.name)}</legend><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${escape(menu.version)}">${isNew?`<input type="hidden" name="id" value="${escape(newOptionId)}">`:''}<label>اسم الإضافة <input name="name" required maxlength="120" value="${escape(option.name)}"></label><label>سعر الإضافة <input name="price" inputmode="decimal" required maxlength="16" value="${escape((option.priceMinor/100).toFixed(2))}"></label><label>تفعيل الإضافة <select name="available" aria-label="تفعيل الإضافة"><option value="true" ${option.available?'selected':''}>مفعّلة</option><option value="false" ${!option.available?'selected':''}>غير مفعّلة</option></select></label><button>${isNew?'إضافة الخيار':'حفظ الإضافة'}</button></fieldset></form>`;
  const optionEditor=membership.permissions.includes('menu:update')?`<h2>تعديل الإضافات</h2>${(item.options??[]).map(option=>optionForm(option)).join('')}${(item.options??[]).length<50?optionForm({name:'',priceMinor:0,available:false},true):'<p>بلغ الصنف الحد الأقصى: 50 إضافة.</p>'}<p>يمكن تعطيل الإضافة دون تغيير الطلبات السابقة. كل حفظ يتطلب أحدث إصدار من المنيو.</p>`:'';
  return page(item.name,`<a href="/manage/${escape(tenantId)}/menu">المنيو</a><p>السعر: ${escape((item.priceMinor/100).toFixed(2))} SAR. الإصدار: ${escape(menu.version)}</p><p>تظل قواعد المخزون وفتح المطعم سارية. هذا النموذج يحافظ على الصورة والإضافات وإعدادات المطعم والطاولات.</p>${form}<h2>الإضافات الحالية</h2><ul>${options}</ul>${optionEditor}${imageForm}`);
}

export function staffStockPage({tenantId,membership,items,catalog,csrf}){
  const names=new Map(catalog.items.map(item=>[item.id,item.name]));
  const sections=items.map(item=>{
    const name=names.get(item.itemId)??item.itemId;
    const state=item.tracked?`المتاح للبيع: ${escape(item.available)}. المحجوز: ${escape(item.held)}.`:'التتبع غير مفعّل؛ الصفر المعروض ليس قياسًا للمخزون الفعلي.';
    const form=membership.permissions.includes('stock:update')?`<form method="post" action="/manage/${escape(tenantId)}/stock/${escape(item.itemId)}"><fieldset><legend>تعديل مخزون ${escape(name)}</legend><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="version" value="${escape(item.version)}"><label>تتبع مخزون ${escape(name)} <select name="tracked"><option value="true" ${item.tracked?'selected':''}>مفعّل</option><option value="false" ${!item.tracked?'selected':''}>غير مفعّل</option></select></label><label>الكمية المتاحة للبيع من ${escape(name)} <input name="available" type="number" min="0" max="1000000" step="1" required value="${escape(item.available)}"></label><button>حفظ مخزون ${escape(name)}</button></fieldset></form>`:'';
    return `<section><h2>${escape(name)}</h2><p>${state}</p><p>الإصدار: ${escape(item.version)}</p>${form}</section>`;
  }).join('');
  return page('مخزون '+tenantId,`<a href="/manage">مطاعمي</a><p>الجرد يضبط المتاح للبيع فقط، خارج الكميات المحجوزة أو المباعة. لا يمسح الحجوزات القائمة. عند تعطيل التتبع يجب أن تكون الكمية صفرًا؛ وقد يُرفض التغيير حتى تسوية الطلبات الجارية.</p>${sections||'<p>لا توجد أصناف.</p>'}`);
}

export function staffChannelsPage({tenantId,channels,csrf}){
  const names={web:'الموقع',chatgpt:'ChatGPT',whatsapp_qr:'واتساب QR',whatsapp_cloud:'واتساب Cloud API'};
  const sections=channels.map(policy=>`<section><h2>${escape(names[policy.channel]??policy.channel)}</h2><p>استقبال الطلبات الجديدة: ${policy.newOrdersEnabled?'مسموح بالإعداد':'متوقف بالإعداد'}. الإصدار: ${escape(policy.version)}</p>${policy.adapterImplemented?`<form method="post" action="/manage/${escape(tenantId)}/channels/${escape(policy.channel)}"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${escape(policy.version)}"><label>استقبال طلبات ${escape(names[policy.channel])} <select name="newOrdersEnabled"><option value="true" ${policy.newOrdersEnabled?'selected':''}>مسموح</option><option value="false" ${!policy.newOrdersEnabled?'selected':''}>متوقف</option></select></label><button>حفظ إعداد القناة</button></form>`:'<p>محول الطلبات لهذه القناة غير مكتمل. هذا لا يغيّر اتصال واتساب أو المكالمات القائمة.</p>'}</section>`).join('');
  return page('قنوات '+tenantId,`<a href="/manage">مطاعمي</a><p>الإيقاف يمنع إنشاء طلبات جديدة فقط. تبقى الطلبات السابقة وحالاتها ومدفوعاتها قابلة للمتابعة. السماح لا يغني عن جاهزية الربط وفتح المطعم.</p>${sections}`);
}

export function staffOrdersPage({tenantId,membership,orders,csrf}){
  const next=order=>({new:['accepted','cancelled'],accepted:['preparing','cancelled'],preparing:['ready','cancelled'],
    ready:[order.mode==='delivery'?'out_for_delivery':'completed','cancelled'],out_for_delivery:['completed','cancelled']}[order.status]??[]);
  const form=(order,action,fields,button)=>`<form method="post" action="/manage/${escape(tenantId)}/orders/${escape(order.number)}/${action}"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="version" value="${escape(order.version)}">${fields}<button>${button}</button></form>`;
  const cards=orders.map(order=>{
    const statuses=next(order);
    const status=membership.permissions.includes('orders:update')&&statuses.length?form(order,'status',`<label>الحالة التالية للطلب ${escape(order.number)} <select name="status">${statuses.map(value=>`<option value="${value}">${label(value)}</option>`).join('')}</select></label>`,'تحديث الحالة'):'';
    const cash=membership.permissions.includes('payments:collect')&&['cash_on_delivery','cash_before','cash_after'].includes(order.paymentMethod)&&order.paymentStatus==='unpaid'&&order.status!=='cancelled'?form(order,'cash','<p>لا تسجّل التحصيل إلا بعد استلام المبلغ نقدًا.</p>','تأكيد استلام المبلغ النقدي'):'';
    const dispatch=membership.permissions.includes('delivery:assign')&&order.mode==='delivery'&&!['completed','cancelled'].includes(order.status)&&order.deliveryStatus!=='delivered'?`<a href="/manage/${escape(tenantId)}/orders/${escape(order.number)}/courier">إسناد مندوب</a>`:'';
    const finance=membership.permissions.includes('payments:read')?`<a href="/manage/${escape(tenantId)}/orders/${escape(order.number)}/finance">السجل المالي</a>`:'';
    const courier=order.mode==='delivery'?`<p>المندوب: ${escape(order.courierName||'لم يُسند')}</p>`:'';
    const detail=Array.isArray(order.items)?`<h3>الأصناف</h3><ul>${order.items.map(item=>`<li>${escape(item.name)} × ${escape(item.quantity)} (${escape((item.totalMinor/100).toFixed(2))} SAR) ${(item.options??[]).map(option=>escape(option.name)).join('، ')}</li>`).join('')}</ul>${order.tableName?`<p>الطاولة: ${escape(order.tableName)}</p>`:''}${order.notes?`<h3>تعليمات الطلب</h3><p>${escape(order.notes)}</p>`:''}`:'';
    return `<article><h2><a href="/manage/${escape(tenantId)}/orders/${escape(order.number)}">${escape(order.number)}</a></h2><p>الحالة: ${label(order.status)}. الدفع: ${label(order.paymentStatus)}.</p><p>الإجمالي: ${escape((order.totalMinor/100).toFixed(2))} SAR. الإصدار: ${escape(order.version)}</p>${courier}${detail}${status}${cash}${finance}${dispatch}</article>`;
  }).join('');
  return page('طلبات '+tenantId,`<nav><a href="/manage">مطاعمي</a> · <a href="/manage/${escape(tenantId)}/orders">تحديث القائمة</a></nav>${membership.tenantStatus==='suspended'?'<p>المطعم موقوف عن العمل الجديد؛ متابعة وتسوية الطلبات القائمة متاحة وفق صلاحياتك.</p>':''}<p>${orders.some(order=>Array.isArray(order.items))?'تفاصيل الأصناف وتعليمات التنفيذ محفوظة كما كانت عند الطلب.':'أحدث 100 طلب.'} هذه واجهة تشغيل أولية؛ تبقى إدارة المطعم الأصلية متاحة للوظائف الأخرى.</p>${cards||'<p>لا توجد طلبات.</p>'}`);
}

const roleNames={owner:'مالك',manager:'مدير',supervisor:'مشرف',kitchen:'مطبخ',cashier:'كاشير',courier:'مندوب'};
const permissionNames={'orders:read':'عرض الطلبات','orders:update':'تحديث الطلبات','menu:read':'عرض المنيو','menu:update':'تعديل المنيو','stock:read':'عرض المخزون','stock:update':'تعديل المخزون','delivery:read':'عرض التوصيل','delivery:assign':'تعيين التوصيل','payments:read':'عرض المدفوعات','payments:collect':'تأكيد التحصيل النقدي','refunds:manage':'إدارة الاسترداد','settings:read':'عرض الإعدادات','settings:update':'تعديل الإعدادات','channels:manage':'إدارة القنوات','members:manage':'إدارة الفريق','couriers:link':'ربط هويات المندوبين بحساباتهم','courier:read':'عرض مهامي كمندوب','courier:update':'تحديث مهامي وتوفري كمندوب','courier:collect':'تأكيد نقد طلباتي كمندوب'};
export function staffMembersPage({tenantId,members,csrf,actorId}){
 const roleSelect=selected=>`<label>الدور <select name="role" aria-label="الدور">${Object.entries(roleNames).map(([key,name])=>`<option value="${key}" ${selected===key?'selected':''}>${name}</option>`).join('')}</select></label>`;
 const enabledSelect=value=>`<label>حالة العضوية <select name="enabled" aria-label="حالة العضوية"><option value="true" ${value?'selected':''}>مفعّلة</option><option value="false" ${!value?'selected':''}>موقوفة</option></select></label>`;
 const rows=members.map(member=>`<section><h2>${escape(member.displayName||member.principalId)}${member.principalId===actorId?' (أنت)':''}</h2><p dir="ltr">${escape(member.principalId)}</p><form method="post" action="/manage/${escape(tenantId)}/members/${escape(member.principalId)}"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${escape(member.version)}"><label>الاسم داخل المطعم <input name="displayName" maxlength="100" value="${escape(member.displayName??'')}"></label>${roleSelect(member.role)}${enabledSelect(member.enabled)}<label>اختيار الصلاحيات <select name="permissionsMode" aria-label="اختيار الصلاحيات"><option value="custom">الصلاحيات المحددة أدناه</option><option value="role">الصلاحيات الافتراضية للدور المختار</option></select></label><fieldset><legend>الصلاحيات التفصيلية</legend>${RESTAURANT_PERMISSIONS.map(permission=>`<label><input type="checkbox" name="perm:${permission}" value="yes" ${member.permissions.includes(permission)?'checked':''}>${permissionNames[permission]}</label>`).join('')}</fieldset><button>حفظ العضوية</button></form></section>`).join('');
 return page('فريق '+tenantId,`<a href="/manage">مطاعمي</a><p>لا يمكن تعطيل آخر مالك نشط. عضوية المالك تشمل جميع الصلاحيات. الاسم المعروض تسمية داخل المطعم ولا يربط حسابات بالبريد أو الهاتف.</p>${rows}<section><h2>إضافة حساب مسجل</h2><p>يجب أن يسجّل الموظف الدخول أولًا ويشارك معرّف حسابه من صفحة الإدارة. لم تُرسل أي دعوة أو رسالة نيابةً عنك.</p><form method="post" action="/manage/${escape(tenantId)}/members"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value=""><input type="hidden" name="permissionsMode" value="role"><label>معرّف حساب الموظف <input name="principalId" required maxlength="36" dir="ltr"></label><label>اسم الموظف داخل المطعم <input name="displayName" maxlength="100"></label>${roleSelect('kitchen')}${enabledSelect(false)}<button>إضافة العضوية</button></form><p>تبدأ العضوية موقوفة افتراضيًا للمراجعة؛ اختر التفعيل حين تتأكد من الحساب والصلاحيات.</p></section>`);
}
export function staffErrorPage(code){
 const messages={invalid_service_modes:'فعّل طريقة خدمة واحدة على الأقل قبل استقبال الطلبات الجديدة.',authentication_required:'انتهت جلسة الدخول أو لم تبدأ بعد. ارجع إلى الإدارة وسجّل الدخول قبل إعادة المحاولة.',tenant_suspended:'المطعم معلّق حاليًا ولا يسمح بهذا الإجراء.',version_conflict:'تغيّرت العضوية. افتح صفحة الفريق من جديد وراجع أحدث البيانات.',catalog_changed:'تغيّر المنيو. حدّث الصفحة قبل إعادة التعديل.',last_owner_required:'لا يمكن تعطيل أو تغيير دور آخر مالك نشط. عيّن مالكًا آخر أولًا.',invalid_owner_permissions:'يجب أن تشمل عضوية المالك جميع الصلاحيات.',forbidden:'لا تملك الصلاحية المطلوبة لهذا الإجراء.',identity_disabled:'الحساب غير متاح أو لم يسجّل الدخول بعد. تحقق من معرّفه.',invalid_request:'تحقق من الحقول المدخلة قبل إعادة المحاولة.',tenant_closed:'المطعم مغلق ولا يمكن تعديل عضوياته.',order_outcome_unknown:'تعذر تأكيد نتيجة التغيير. حدّث الصفحة وتحقق من الحالة قبل إعادة الإرسال.'};
 return messages[code]?page('تعذر إتمام التغيير',`<p>${messages[code]}</p><a href="/manage">العودة إلى الإدارة</a>`):null;
}

export function staffProfilePage({tenantId,profile,canUpdate,csrf}){
 const fields=[['name','اسم المطعم العام',120],['description','وصف المطعم',2000],['address','عنوان المطعم',1000],['phone','هاتف المطعم',40],['openingHours','ساعات العمل (نص معلوماتي)',1000],['pickupInstructions','تعليمات الاستلام',2000]];
 const controls=fields.map(([key,label,max])=>`<p><label>${label}<textarea name="${key}" maxlength="${max}" ${canUpdate?'':'readonly'}>${escape(profile[key])}</textarea></label></p>`).join('');
 return page('بيانات المطعم العامة',`<p>${escape(tenantId)}</p><p>تظهر هذه المعلومات للعملاء. ساعات العمل نص معلوماتي ولا تُغلق الطلبات تلقائيًا. هذا النموذج لا يغيّر الضرائب أو الأسعار أو وسائل الدفع أو القالب.</p><form method="post" action="/manage/${escape(tenantId)}/profile"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${profile.version}">${controls}${canUpdate?'<label><input type="checkbox" name="reviewed" value="yes" required>راجعت المعلومات العامة التي ستُنشر</label><button>حفظ البيانات العامة</button>':''}</form><a href="/manage">رجوع</a>`);
}

export function staffDeliveryPage({tenantId,data,regions,cities,districts,region='',city='',search='',pageIndex=0,canUpdate,csrf}){
 const base=`/manage/${escape(tenantId)}/delivery`,hidden=`<input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${data.version}">`,review='<label><input type="checkbox" name="reviewed" value="yes" required>راجعت أثر التغيير على الطلبات الجديدة</label>';
 const amount=value=>(value/100).toFixed(2),priceInput=(name,label,value)=>`<label>${label}<input name="${name}" value="${value===null?'':amount(value)}" inputmode="decimal" ${canUpdate?'':'readonly'}></label>`;
 const opts=(rows,selected)=>'<option value="">اختر</option>'+rows.map(v=>`<option value="${escape(v.id)}" ${v.id===selected?'selected':''}>${escape(v.nameAr||v.nameEn||v.id)}</option>`).join('');
 const selector=`<form method="get" action="${base}"><label>المنطقة<select name="region" aria-label="المنطقة">${opts(regions.regions,region)}</select></label><button>عرض المدن</button></form>${region?`<form method="get" action="${base}"><input type="hidden" name="region" value="${escape(region)}"><label>المدينة<select name="city" aria-label="المدينة">${opts(cities?.cities??[],city)}</select></label><button>عرض الأحياء</button></form>`:''}`;
 const pricing=`<h2>طريقة التسعير</h2><form method="post" action="${base}/pricing">${hidden}<label>طريقة التسعير<select name="mode" aria-label="طريقة التسعير" ${canUpdate?'':'disabled'}><option value="flat" ${data.mode==='flat'?'selected':''}>رسم موحّد</option><option value="district" ${data.mode==='district'?'selected':''}>حسب الحي</option></select></label>${priceInput('feeMinor','الرسم الموحّد بالريال',data.feeMinor)}${priceInput('minimumMinor','الحد الأدنى بالريال',data.minimumMinor)}${canUpdate?review+'<button>حفظ تسعير التوصيل</button>':''}</form>`;
 const zoneForm=(zone,select)=>`<form method="post" action="${base}/zone">${hidden}${select??`<input type="hidden" name="districtId" value="${escape(zone.districtId)}">`}<label>حالة الحي<select name="enabled" aria-label="حالة الحي" ${canUpdate?'':'disabled'}><option value="false" ${!zone.enabled?'selected':''}>معطّل</option>${zone.active!==false?`<option value="true" ${zone.enabled?'selected':''}>مفعّل</option>`:zone.enabled?'<option value="true" selected disabled>غير نشط؛ اختر التعطيل</option>':''}</select></label>${priceInput('feeMinor','رسم الحي بالريال',zone.feeMinor)}${canUpdate?review+'<button>حفظ حي التوصيل</button>':''}</form>`;
 const add=canUpdate&&city?`<h2>تهيئة حي</h2>${zoneForm({enabled:false,feeMinor:null},`<label>الحي<select name="districtId" aria-label="الحي" required>${opts(districts?.districts??[],'')}</select></label>`)}`:'';
 const matches=data.zones.filter(v=>!search||`${v.nameAr} ${v.nameEn} ${v.cityName} ${v.districtId}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(matches.length/50)),index=Math.min(pageIndex,pages-1);
 const rows=matches.slice(index*50,index*50+50).map(v=>`<section><h3>${escape(v.nameAr||v.nameEn||v.districtId)}</h3><p>${escape(v.regionName)} · ${escape(v.cityName)} · <span dir="ltr">${escape(v.districtId)}</span></p><p>${v.active?'':'الحي أو أحد والديه غير نشط. '}${v.feeMinor===null?'الرسم غير محدد':v.feeMinor===0?'توصيل مجاني':amount(v.feeMinor)+' ر.س'}</p>${zoneForm(v)}</section>`).join('');
 const link=page=>base+'?'+new URLSearchParams({filter:search,page:String(page+1)}).toString();
 return page('مناطق ورسوم التوصيل',`<p>${escape(tenantId)}</p><p>التوصيل ${data.enabled?'مفعّل':'متوقف'}، استقبال الطلبات ${data.acceptingOrders?'مفعّل':'متوقف'}. قيود الموقع الحالية محفوظة${data.radiusKm?'، بنطاق '+data.radiusKm+' كم':''}.</p><p>في وضع الأحياء لا يقبل الحي غير المهيأ أو المعطّل توصيلًا. صفر يعني توصيلًا مجانيًا؛ الحقل الفارغ ليس صفرًا. التغيير يخص الطلبات الجديدة في جميع القنوات ولا يغيّر رسوم الطلبات السابقة.</p>${pricing}<h2>اختيار حي من البيانات الحالية</h2><p>${escape(regions.source.name)} (${escape(regions.source.license)}): ${escape(regions.source.notice)}</p>${selector}${add}<h2>الأحياء المهيأة</h2><form method="get" action="${base}"><label>بحث الأحياء<input name="filter" maxlength="120" value="${escape(search)}"></label><button>بحث</button></form>${rows||'<p>لا توجد أحياء مطابقة.</p>'}<p>${index+1} / ${pages} ${index>0?`<a href="${escape(link(index-1))}">السابق</a>`:''} ${index+1<pages?`<a href="${escape(link(index+1))}">التالي</a>`:''}</p><a href="/manage">رجوع</a>`);
}

export function staffDispatchPage({tenantId,order,couriers,csrf}){
 const availability={available:'متاح',busy:'مشغول',offline:'غير متصل'};
 const options=couriers.filter(v=>v.active).map(v=>`<option value="${escape(v.id)}">${escape(v.name)} · ${escape(availability[v.availability]??v.availability)} · ${escape(v.id.slice(-8))}</option>`).join('');
 return page('إسناد مندوب للطلب',`<p>المطعم: ${escape(tenantId)} · الطلب: ${escape(order.number)}</p><p>المندوب الحالي: ${escape(order.courierName||'لم يُسند')}</p><p>إعادة الإسناد تنقل صلاحية متابعة الطلب من المندوب السابق، ولا تسجل تحصيلًا أو تسليمًا. حالة التوفر وصف حالي وليست ضمانًا لاستلام العمل.</p><form method="post" action="/manage/${escape(tenantId)}/orders/${escape(order.number)}/courier"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="version" value="${order.version}"><label>المندوب المطلوب<select name="courierId" aria-label="المندوب المطلوب" required><option value="" disabled selected>اختر إجراءً</option><option value="__remove__">إلغاء الإسناد</option>${options}</select></label><label><input type="checkbox" name="reviewed" value="yes" required>راجعت المندوب المطلوب وأثر إعادة الإسناد</label><button>تأكيد إسناد المندوب</button></form><p>أول 500 مندوب مسجل في النواة الحالية؛ لا تُنشأ حسابات أو كلمات مرور هنا.</p><a href="/manage/${escape(tenantId)}/orders/${escape(order.number)}">رجوع إلى الطلب</a>`);
}

export function staffServicePage({tenantId,data,canUpdate,csrf}){
 const fields={acceptingOrders:'استقبال الطلبات الجديدة',deliveryEnabled:'التوصيل',pickupEnabled:'الاستلام من المطعم',tableEnabled:'طلبات الطاولات'};
 return page('استقبال الطلبات وطرق الخدمة',`<p>${escape(tenantId)}</p><p>الإيقاف يمنع قبول طلبات جديدة فقط؛ لا يلغي الطلبات المسجلة أو يغيّر الأسعار والضرائب وروابط الطاولات. ساعات العمل المكتوبة لا تغلق الاستقبال تلقائيًا.</p><form method="post" action="/manage/${escape(tenantId)}/service"><input type="hidden" name="csrf" value="${escape(csrf)}"><input type="hidden" name="expectedVersion" value="${data.version}">${Object.entries(fields).map(([key,label])=>`<p><label>${label}<select aria-label="${label}" name="${key}" ${canUpdate?'':'disabled'}><option value="true" ${data[key]?'selected':''}>مفعّل</option><option value="false" ${!data[key]?'selected':''}>متوقف</option></select></label></p>`).join('')}${canUpdate?'<label><input type="checkbox" name="reviewed" value="yes" required>راجعت أثر التغيير على الطلبات الجديدة</label><button>حفظ سياسة الاستقبال</button>':''}</form><a href="/manage">رجوع</a>`);
}

export function staffFinancePage({tenantId,data,canManage=false}){
 const money=value=>escape((value/100).toFixed(2))+' SAR',refundLabel={requested:'طلب استرداد مسجل',processing:'قيد المعالجة',succeeded:'استرداد مؤكد',failed:'فشل الاسترداد',review:'يحتاج مراجعة',manual_reported:'إبلاغ يدوي غير مؤكد من المزود'};
 const totals={'إجمالي الطلب':data.totalMinor,'المبلغ المحصل المؤكد':data.capturedMinor,'المبلغ المحجوز للاسترداد':data.reservedMinor,'المبلغ المسترد المؤكد':data.refundedMinor,'المتاح لطلب استرداد':data.availableMinor};
 return page('المدفوعات والاستردادات',`<p>${escape(tenantId)} • ${escape(data.number)}</p>${data.demo?'<p>طلب تجريبي؛ ليس حركة أموال حقيقية.</p>':''}<p>حالة الدفع: ${label(data.paymentStatus)} • المزود: ${escape(data.provider||'غير مرتبط')}</p>${Object.entries(totals).map(([name,value])=>`<p>${name}: ${money(value)}</p>`).join('')}<p>المحجوز يشمل الاستردادات المؤكدة والمعلقة غير الفاشلة. هذه الشاشة للعرض ولا ترسل أموالًا.</p><h2>سجل الاستردادات • حتى 100 عملية</h2>${data.refunds.length?data.refunds.map(r=>`<article><h3>${escape(refundLabel[r.status]??'يحتاج مراجعة')}</h3><p>${money(r.amountMinor)} • الضريبة ضمن المبلغ: ${money(r.taxMinor)}</p><p dir="ltr">${escape(r.id)}</p><p>${escape(r.updatedAt)}</p>${canManage?`<a href="/manage/${escape(tenantId)}/orders/${escape(data.number)}/refunds/${escape(r.id)}">إدارة عملية الاسترداد</a>`:''}</article>`).join(''):'<p>لا توجد عمليات استرداد مسجلة.</p>'}<a href="/manage/${escape(tenantId)}/orders/${escape(data.number)}">رجوع إلى الطلب</a>`);
}

export function refundActions(r){
 return [
  !r.authorized&&!r.submitted&&['requested','review'].includes(r.status)&&r.capability.automatic&&r.capturedMinor===r.orderTotalMinor?'authorize':null,
  r.status==='review'&&!r.submitted&&r.capturedMinor>=r.amountMinor?'manual':null,
  r.status==='review'&&r.submitted&&!r.providerReference?'verify':null,
  r.providerReference&&!['succeeded','failed','manual_reported'].includes(r.status)?'refresh':null,
 ].filter(Boolean);
}
const refundActionLabels={authorize:'التصريح بتنفيذ الاسترداد',manual:'تسجيل استرداد يدوي سابق',verify:'التحقق من مرجع المزود',refresh:'مراجعة حالة المزود'};
export function staffRefundPage({tenantId,data,csrf,review,unknown=false}){
 const path=`/manage/${encodeURIComponent(tenantId)}/orders/${encodeURIComponent(data.number)}/refunds/${encodeURIComponent(data.id)}`;
 const hidden=(key,value)=>`<input type="hidden" name="${key}" value="${escape(value)}">`;
 const summary=`<p>المطعم: ${escape(tenantId)} • الطلب: ${escape(data.number)}</p><p dir="ltr">${escape(data.id)}</p><p>المبلغ: ${(data.amountMinor/100).toFixed(2)} SAR • المزود: ${escape(data.provider||'غير مرتبط')} • الإصدار: ${data.version}</p><p>${data.demo?'طلب تجريبي؛ ليس حركة أموال حقيقية.':'طلب فعلي؛ التصريح قد يرسل أموالًا حقيقية.'}</p><p>الحالة: ${escape(data.status)} • سبب الطلب: ${escape(data.reason)}</p>${['providerReference','manualReference','resolutionReason'].map(key=>data[key]?`<p>${escape(data[key])}</p>`:'').join('')}<p>الإبلاغ اليدوي لا يساوي تأكيد المزود. التحقق والتحديث لا ينشئان دفعة جديدة.</p>`;
 let form;
 if(review){
  const input={action:review.action,version:data.version,amountMinor:data.amountMinor,currency:data.currency,provider:data.provider,demo:String(data.demo),...(review.reference?{reference:review.reference,reason:review.reason}:{})};
  form=`<h2>${escape(refundActionLabels[review.action])}</h2>${review.reference?`<p>المرجع: ${escape(review.reference)}</p><p>الملاحظة: ${escape(review.reason)}</p>`:''}<p>${review.action==='authorize'?'هذا تصريح بتنفيذ المبلغ المذكور بواسطة عامل الاسترداد. إلغاء الطلب وحده لا يصرح بتحويل الأموال.':review.action==='manual'?'سجّل فقط استردادًا نفذته سابقًا خارج التطبيق؛ هذا الإجراء لا ينفذ التحويل.':'قراءة حالة العملية الموجودة لدى المزود فقط.'}</p><form method="post" action="${path}/execute">${hidden('csrf',csrf)}${Object.entries(input).map(([key,value])=>hidden(key,value)).join('')}<label><input type="checkbox" name="reviewed" value="yes" required>راجعت المبلغ والمزود ووضع التجربة وأؤكد هذا الإجراء</label><button>تأكيد إجراء الاسترداد</button></form><a href="${path}">إلغاء المراجعة</a>`;
 }else{
  form=refundActions(data).map(action=>`<form method="post" action="${path}/review">${hidden('csrf',csrf)}${hidden('action',action)}${['manual','verify'].includes(action)?'<label>مرجع الاسترداد<input name="reference" aria-label="مرجع الاسترداد" required minlength="3" maxlength="200"></label><label>سبب الإجراء<textarea name="reason" aria-label="سبب الإجراء" required minlength="3" maxlength="1000"></textarea></label>':''}<button>مراجعة ${escape(refundActionLabels[action])}</button></form>`).join('');
 }
 return page('مراجعة عملية الاسترداد',`${unknown?'<p role="alert">تعذر تأكيد نتيجة الإرسال. هذه قراءة للعملية نفسها؛ لم نكرر الإرسال تلقائيًا. راجع حالتها قبل أي إجراء جديد.</p>':''}${summary}${form}<a href="${path}">تحديث عملية الاسترداد</a> <a href="/manage/${escape(tenantId)}/orders/${escape(data.number)}/finance">السجل المالي</a>`);
}
